// <auto-generated />
using System;
using BlazorWebAssemblyApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorWebAssemblyApp.Server.Migrations
{
    [DbContext(typeof(ShakelyContext))]
    [Migration("20220628171632_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("BlazorWebAssemblyApp.Server.Models.Price", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AdjustedClose")
                        .HasColumnType("REAL");

                    b.Property<double?>("Close")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CurrentHoldings")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double?>("High")
                        .HasColumnType("REAL");

                    b.Property<double?>("Low")
                        .HasColumnType("REAL");

                    b.Property<double?>("Open")
                        .HasColumnType("REAL");

                    b.Property<double?>("Pct_Change")
                        .HasColumnType("REAL");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Symbol");

                    b.ToTable("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
